Repository kokuwaio/k3s-maven-plugin, pull requests merged in 2022-08, with the labels that each got.

#120 Update k3s default version
  docs/goal/create.md
  src/main/java/io/kokuwa/maven/k3s/mojo/CreateMojo.java
Labels: dependencies

#121 Handle images in parallel, fix #105
  src/main/java/io/kokuwa/maven/k3s/mojo/ImageMojo.java
  src/test/java/io/kokuwa/maven/k3s/mojo/ImageMojoTest.java
Labels: enhancement

#122 Unify github actions
  .github/workflows/ci.yaml
  .github/workflows/codeql.yaml
  .github/workflows/lint.yaml
  .github/workflows/pullrequest.yaml
  .github/workflows/release.yaml
  .github/workflows/snapshot.yaml
  README.md
Labels: enhancement, github_actions

#126 Fix pod state check for jobs
  README.md
  src/it/cert-manager/pom.xml
  src/it/cert-manager/src/test/charts/cert-manager/Chart.yaml
  src/it/cert-manager/src/test/charts/cert-manager/values.yaml
  src/it/cert-manager/src/test/java/io/kokuwa/maven/k3s/PodIT.java
  src/main/java/io/kokuwa/maven/k3s/util/Kubernetes.java
Labels: enhancement, patch

#127 Remove duplicate bouncycastle dependency
  pom.xml
Labels: dependencies

#128 Fix flaky test
  src/main/java/io/kokuwa/maven/k3s/mojo/ImageMojo.java
  src/test/java/io/kokuwa/maven/k3s/mojo/ImageMojoTest.java
Labels: bug
